

name: CI Pipeline 

on: push

jobs:
  project-testing: 
    runs-on: ubuntu-latest  

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt
          
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt

      - name: run pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro
  